# Generated by Django 3.2.7 on 2021-09-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastupdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
