# Generated by Django 3.2.7 on 2021-09-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followernumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
