# Generated by Django 3.2.7 on 2021-09-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_followernumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lastupdate',
        ),
    ]
