# Generated by Django 3.2.7 on 2021-09-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
