# Generated by Django 3.2.7 on 2021-09-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lastupdate',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
