# Generated by Django 3.2.7 on 2021-09-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210911_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repname',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='starrating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
