# Generated by Django 3.2.7 on 2021-09-11 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210911_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['repname']},
        ),
    ]
