# Generated by Django 3.2.7 on 2021-09-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_repository_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='starrating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
